sudo: false
language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install flake8
  - python setup.py install
script: 
  - coverage run setup.py test
  - flake8 .
after_success:
  coveralls
